apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-dev
  namespace: default
spec:
  interval: 10m0s
  path: ./apps/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hello-nest
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://k9s-helm-repository-bucket-dev.s3.eu-west-1.amazonaws.com/hello-nest/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://k9s-helm-repository-bucket-dev.s3.eu-west-1.amazonaws.com/app/charts
