apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: infrastructure

resources: 
  - ../base
  - nginx-config.yaml

patchesStrategicMerge: []
  #- nginx-ingress-controller.yaml
  