apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: infrastructure
spec:
  values:
    replicaCount: 1
    defaultBackend:
      replicaCount: 1
