apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: infrastructure
spec:
  values:
    kind: Deployment
    replicaCount: 1
    extraArgs: 
      worker_processes: 1
    defaultBackend:
      enabled: false

