apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: apps
  labels:
    alertmanagerConfig: alertmanager-config
spec:
  route:
    groupBy: ['job']
    groupWait: 3s
    groupInterval: 3s
    repeatInterval: 3s
    receiver: 'slack'
  receivers:
    - name: 'slack'
      slackConfigs:
        - apiURL:
            name: slack-url
            key: address
---
apiVersion: v1
data:
  address: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzUEtBM0JSTlovQjAzUVNRNUtSQkovWkZ5Q0FEdDNkRHpkdGVEeWdBUW5WZnZr
kind: Secret
metadata:
  name: slack-url
  namespace: apps
