# https://doc.crds.dev/github.com/prometheus-operator/kube-prometheus/monitoring.coreos.com/AlertmanagerConfig/v1alpha1@v0.7.0
# https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1alpha1.AlertmanagerConfigSpec
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config-web-svc
  namespace: monitoring
  labels:
    alertmanagerConfig: alertmanager-config
spec:
  route:
    groupBy: ['job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'slack-web-svc'
  receivers:
    - name: slack-web-svc
      slackConfigs:
        - apiURL:
            name: slack-url-web-svc
            key: address
          sendResolved: true
---
apiVersion: v1
data:
  address: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAzUEtBM0JSTlovQjAzUUxMOTZCTjIvYm1KQ2I2cmlXM25FSHhPcml2dTR3cUJS
kind: Secret
metadata:
  name: slack-url-web-svc
  namespace: monitoring
