apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: monitoring
spec:
  replicas: 1
  alertmanagerConfigSelector:
    matchLabels:
      alertmanagerConfig: alertmanager-config
  alertmanagerConfigNamespaceSelector: {}
#  alertmanagerConfiguration:
#    name: alertmanager-config
