apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
spec:
  interval: 1m0s
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      version: 1.22.1
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
      interval: 10m0s
  values:
    slack:
      user: flagger
      channel: '#flagger-dev'
      url: https://hooks.slack.com/services/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
    meshProvider: nginx
