apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  interval: 1m0s
  releaseName: grafana-operator
  chart:
    spec:
      chart: grafana-operator
      version: 2.6.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
  values:
    operator:
      scanNamespaces:
        - default
        - apps
    grafana:
      enabled: false
      replicaCount: 1
      skipCreateAdminAccount: false
    extraDeploy:
      - apiVersion: integreatly.org/v1alpha1
        kind: GrafanaDataSource
        metadata:
          name: prometheus-datasource
        spec:
          name: middleware.yaml
          datasources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://prometheus-k8s.monitoring.svc:9090
              isDefault: true
              version: 1
              editable: true
              jsonData:
                tlsSkipVerify: true
                timeInterval: 10s
      - apiVersion: integreatly.org/v1alpha1
        kind: Grafana
        metadata:
          name: grafana
        spec:
          deployment:
            securityContext:
              runAsUser: 1001
              fsGroup: 1001
            containerSecurityContext:
              runAsUser: 1001
              allowPrivilegeEscalation: false
          service:
            type: LoadBalancer
          ingress:
            enabled: false
          config:
            log:
              mode: "console"
              level: "warn"
            security:
              admin_user: "admin"
              admin_password: "admin"
            auth.anonymous:
              enabled: true
          dashboardLabelSelector:
            - matchExpressions:
                - { key: app, operator: In, values: [ grafana ] }

