apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: infrastructure
spec:
  interval: 1m0s
  releaseName: kube-prometheus
  chart:
    spec:
      chart: kube-prometheus
      version: 8.0.11
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
  values:
    alertmanager:
      enabled: true
      configSelector:
        matchLabels:
          alertmanagerConfig: 'true'
      configNamespaceSelector: 
        matchLabels: {}