apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 1m0s
  releaseName: metrics-server
  chart:
    spec:
      chart: metrics-server
      version: 6.0.9
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
  values:
    apiService:
      create: true 
    extraArgs:
      - --kubelet-insecure-tls
