apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  interval: 1m0s
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 9.2.25
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
