apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: infrastructure
spec:
  interval: 10m0s
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: nginx-ingress-controller
              namespace: "default"
            rules:
              - apiGroups:
                  - coordination.k8s.io
                resources:
                  - leases
                verbs:
                  - list
                  - watch
                  - get
                  - update
                  - apply
                  - patch
                  - delete
                  - create