apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: default
spec:
  interval: 10m0s
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 9.2.23
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
