apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress-controller
  namespace: infrastructure
spec:
  interval: 1m0s
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      version: 9.2.23
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
  # Remove the patch below when the issue is fixed: https://github.com/bitnami/charts/issues/11192
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              group: rbac.authorization.k8s.io
              kind: ClusterRole
              name: nginx-ingress-controller
            patch:
              - op: add
                path: /rules/-
                value: 
                  apiGroups:
                    - coordination.k8s.io
                  resources:
                    - leases
                  verbs:
                    - list
                    - watch
                    - get
                    - update
                    - apply
                    - patch
                    - delete
                    - create
