apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-controller
  namespace: default
spec:
  interval: 10m0s
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m0s
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              group: rbac.authorization.k8s.io
              kind: ClusterRole
              name: nginx-ingress-controller
            patch:
              - op: add
                path: /metadata/labels
                value:
                  msg: hello-patch
              - op: add
                path: /rules/-
                value: 
                  apiGroups:
                    - coordination.k8s.io
                  resources:
                    - leases
                  verbs:
                    - list
                    - watch
                    - get
                    - update
                    - apply
                    - patch
                    - delete
                    - create
