apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
spec:
  interval: 1m0s
  releaseName: nginx-ingress
  timeout: 30s
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-stable
        namespace: flux-system
      interval: 10m0s
  values:
    controller:
      ingressClass: nginx-ingress
      service:
        type: ClusterIP
