# https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/
controller:
  ingressClass: nginx-ingress
  service:
    type: ClusterIP
  config:
    name: nginx-ingress
    entries: 
      worker-processes: "1"