apiVersion: v2
name: app
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
appVersion: "0.0.1"
dependencies:
  - name: hello-nest
    version: 0.0.3
    alias: hello-nest
    repository: https://k9s-helm-repository-bucket-dev.s3.eu-west-1.amazonaws.com/hello-nest/charts

