apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - git::https://github.com/grafana-operator/grafana-operator.git/deploy//manifests?ref=v4.5.1
  - grafana.yaml
