operator:
  scanNamespaces:
    - default
    - apps
grafana:
  enabled: false
  replicaCount: 1
  skipCreateAdminAccount: false
extraDeploy:
  - apiVersion: integreatly.org/v1alpha1
    kind: GrafanaDataSource
    metadata:
      name: example-grafanadatasource
    spec:
      name: middleware.yaml
      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-k8s.monitoring.svc:9090
          isDefault: true
          version: 1
          editable: true
          jsonData:
            tlsSkipVerify: true
            timeInterval: "5s"
  - apiVersion: integreatly.org/v1alpha1
    kind: Grafana
    metadata:
      name: grafana
    spec:
      deployment:
        securityContext:
          runAsUser: 1001
          fsGroup: 1001
        containerSecurityContext:
          runAsUser: 1001
          allowPrivilegeEscalation: false
      service:
        type: LoadBalancer
      ingress:
        enabled: false
      config:
        log:
          mode: "console"
          level: "warn"
        security:
          admin_user: "admin"
          admin_password: "admin"
        auth.anonymous:
          enabled: true
      dashboardLabelSelector:
        - matchExpressions:
            - { key: app, operator: In, values: [ grafana ] }
