apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-sync
spec:
  interval: 1m0s
  path: ./apps/dev
  prune: true
  dependsOn:
    - name: infrastructure
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
