apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hello-nest
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://k9s-helm-repository-bucket-dev.s3.eu-west-1.amazonaws.com/hello-nest/charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://k9s-helm-repository-bucket-dev.s3.eu-west-1.amazonaws.com/app/charts
