apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-nest
  namespace: app
spec:
  releaseName: app
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
