apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-svc
spec:
  chart:
    spec:
      version: 0.1.23
  values:
    app:
      replicaCount: 2
    prometheus:
      alerting:
        memoryUsage:
          thresholdRatio: 0.5
