apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-nest
spec:
  interval: 5m0s
  chart:
    spec:
      chart: hello-nest
      version: '0.0.3'
      sourceRef:
        kind: HelmRepository
        name: hello-nest
        namespace: app
      interval: 1m0s
  test:
    enable: true
    ignoreFailures: false
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    app:
      replicaCount: 3
