apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-nest
spec:
  interval: 5m0s
  chart:
    spec:
      chart: hello-nest
      version: 0.0.4
      sourceRef:
        kind: HelmRepository
        name: hello-nest
        namespace: app
      interval: 1m0s
  values:
    app:
      replicaCount: 3
