apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
spec:
  interval: 2m0s
  releaseName: hello-nest
  chart:
    spec:
      chart: hello-nest
      version: 0.0.8
      sourceRef:
        kind: HelmRepository
        name: hello-nest
        namespace: app
      interval: 1m0s
  test:
    enable: true
    ignoreFailures: false
  install:
    replace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    app:
      replicaCount: 3
