apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: web-svc
spec:
  interval: 1m0s
  releaseName: app
  chart:
    spec:
      chart: web-svc
      version: 0.1.21
      sourceRef:
        kind: HelmRepository
        name: web-svc
        namespace: flux-system
      interval: 1m0s
  test:
    enable: true
    ignoreFailures: false
  install:
    replace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    app:
      replicaCount: 3
  postRender:
    patches: []
