apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - ../base

helmChartInflationGenerator:
  - chartName: hello-nest
    chartRepoUrl: https://k9s-helm-repository-bucket-dev.s3.eu-west-1.amazonaws.com/hello-nest/charts
    chartVersion: 0.0.3
    releaseName: nest
    releaseNamespace: app
